# Generated by Django 5.1.1 on 2024-10-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appLocation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="lodgement_id",
            new_name="lodgement",
        ),
        migrations.RenameField(
            model_name="lodgement",
            old_name="quartier_id",
            new_name="quartier",
        ),
        migrations.RenameField(
            model_name="lodgement",
            old_name="type_lodgement_id",
            new_name="type_lodgement",
        ),
    ]
