# Generated by Django 5.1.1 on 2024-10-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appLocation", "0002_rename_lodgement_id_location_lodgement_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Type_lodgement",
            new_name="TypeLodgement",
        ),
    ]
