# Generated by Django 5.1.1 on 2024-10-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLocation', '0003_rename_type_lodgement_typelodgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='typelodgement',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
