# Generated by Django 5.1.1 on 2024-10-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appLocation", "0004_typelodgement_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="lodgement",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
