# Generated by Django 5.1.1 on 2024-10-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
    ]
