# Generated by Django 5.1.2 on 2024-11-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default="users/pas_d'image_user.jpeg",
                null=True,
                upload_to="users/",
            ),
        ),
    ]
