# Generated by Django 5.1.2 on 2024-11-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0002_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="users/pas_d'image_user.jpg", upload_to="users/"
            ),
        ),
    ]
