# Generated by Django 5.1.1 on 2024-10-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0002_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
