# Generated by Django 5.1.1 on 2024-10-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0003_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=50),
        ),
    ]
