# Generated by Django 5.1.2 on 2024-11-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0004_alter_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
    ]
