# Generated by Django 5.1.1 on 2024-10-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
