# Generated by Django 5.1.2 on 2024-11-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0005_remove_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default="pas_d'image_user.jpg", upload_to="users/"),
        ),
    ]
