# Generated by Django 5.1.2 on 2024-11-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0007_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(default="pas_d'image_user.jpg", upload_to="users/"),
        ),
    ]
