# Generated by Django 5.1.1 on 2024-10-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Locator",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Lodgement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(null=True)),
                ("nbrRooms", models.IntegerField()),
                ("superficies", models.FloatField()),
                ("address", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Quartier",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name="TypeLodgement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=30)),
                ("price", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_begin", models.DateTimeField()),
                ("date_end", models.DateTimeField()),
                (
                    "locator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations_loc",
                        to="app_location.locator",
                    ),
                ),
                (
                    "lodgement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations_lodg",
                        to="app_location.lodgement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lodgement",
            name="quartier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lodgements",
                to="app_location.quartier",
            ),
        ),
        migrations.AddField(
            model_name="lodgement",
            name="type_lodgement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lodgements",
                to="app_location.typelodgement",
            ),
        ),
    ]
