# Generated by Django 5.1.1 on 2024-10-27 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_location", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="locator",
        ),
        migrations.RemoveField(
            model_name="location",
            name="lodgement",
        ),
        migrations.RemoveField(
            model_name="lodgement",
            name="quartier",
        ),
        migrations.RemoveField(
            model_name="lodgement",
            name="type_lodgement",
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nbrRooms", models.IntegerField()),
                ("type_house", models.TextField(null=True)),
                ("quarter", models.TextField()),
                ("address", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("superficies", models.FloatField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="houses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_payment", models.DateTimeField()),
                ("type_payment", models.TextField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_rent", models.DateTimeField()),
                ("date_begin", models.DateTimeField()),
                ("date_end", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paid",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_house",
                        to="app_location.house",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="app_location.payment",
                    ),
                ),
                (
                    "rental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rented",
                        to="app_location.rental",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Locator",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="Quartier",
        ),
        migrations.DeleteModel(
            name="Lodgement",
        ),
        migrations.DeleteModel(
            name="TypeLodgement",
        ),
    ]
