# Generated by Django 5.1.2 on 2024-11-05 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_location", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="house",
            field=models.ForeignKey(
                default=17,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rented",
                to="app_location.house",
            ),
            preserve_default=False,
        ),
    ]
