# Generated by Django 5.1.2 on 2024-11-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_location", "0003_rental_house"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="image",
            field=models.ImageField(
                default="pas_d'image_house_selectionnee.jpg", upload_to="houses/"
            ),
        ),
    ]
