# Generated by Django 5.1.2 on 2024-11-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_location", "0004_house_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="availability",
            field=models.BooleanField(default=True),
        ),
    ]
