# Generated by Django 5.1.2 on 2024-11-09 10:35

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_location", "0006_alter_rental_date_begin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="date_begin",
            field=models.DateTimeField(default=datetime.date(2024, 11, 9)),
        ),
    ]
