# Generated by Django 5.1.2 on 2024-11-09 10:36

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_location", "0007_alter_rental_date_begin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="date_begin",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 9, 10, 36, 13, 554503, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
