# Generated by Django 5.1.2 on 2024-11-11 08:54

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_location", "0011_alter_house_image_alter_rental_date_begin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="date_begin",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 11, 8, 54, 12, 552187, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="date_rent",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 11, 8, 54, 12, 552159, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
