# Generated by Django 5.1.2 on 2024-11-11 09:03

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_location", "0013_alter_rental_date_begin_alter_rental_date_rent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="date_begin",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 11, 9, 3, 23, 132315, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="date_rent",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 11, 9, 3, 23, 132289, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
