# Generated by Django 5.1.2 on 2024-11-12 11:46

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_location", "0015_alter_rental_date_begin_alter_rental_date_rent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="type_house",
            field=models.CharField(
                choices=[
                    ("appartement", "Appartement"),
                    ("chalet", "Chalet"),
                    ("ferme", "Ferme"),
                    ("maison_de_campage", "Maison de campage"),
                    ("maison_en_etage ", "Maison en etage "),
                    ("maison_en_pailles ", "Maison en pailles"),
                    ("maison_en_planche ", "Maison en planche "),
                    ("penthouse ", "Penthouse"),
                    ("villa ", "Villa "),
                    ("studio ", "Studio "),
                ],
                default="appartement",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="date_begin",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 12, 11, 46, 24, 587060, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="date_rent",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 12, 11, 46, 24, 587030, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
