# Generated by Django 5.1.2 on 2024-11-12 12:09

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_location",
            "0016_alter_house_type_house_alter_rental_date_begin_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="type_payment",
            field=models.TextField(
                choices=[
                    ("carte_bancaire", "Carte bancaire"),
                    ("devise", "Devise"),
                    ("lumicash", "Lumicash"),
                    ("carte_visa", "Carte visa"),
                ],
                default="devise",
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="date_begin",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 12, 12, 9, 44, 464928, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="date_rent",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 12, 12, 9, 44, 464900, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
