# Generated by Django 5.1.2 on 2024-11-12 12:10

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_location",
            "0017_alter_payment_type_payment_alter_rental_date_begin_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="date_begin",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 12, 12, 10, 53, 600171, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="date_rent",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 12, 12, 10, 53, 600140, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
