# Generated by Django 5.1.2 on 2024-11-21 09:52

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_location", "0020_alter_house_user_alter_rental_date_begin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="date_begin",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 21, 9, 52, 23, 861582, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="date_rent",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 21, 9, 52, 23, 861540, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
